// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomationTriggerKind } from "./AutomationTriggerKind";

export type AutomationOrigin = { kind: AutomationTriggerKind,
/**
 * Tool, worker, or integration that launched this automated session.
 */
source?: string,
/**
 * Repository name in `owner/repo` form, when the trigger came from GitHub.
 */
repository?: string,
/**
 * GitHub issue or pull request number associated with the trigger.
 */
issue_number?: bigint,
/**
 * Label that triggered automation, such as `every-code`.
 */
label?: string,
/**
 * GitHub event delivery id, webhook id, or local request id.
 */
event_id?: string,
/**
 * Actor reported by the source system as applying the trigger.
 */
actor?: string,
/**
 * Direct URL to the triggering issue, PR, event, or worker record.
 */
url?: string, };
