// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type BrowserSnapshotEvent = { 
/**
 * JSON serialization of the browser snapshot metadata.
 */
snapshot: JsonValue, 
/**
 * URL associated with the snapshot, if available.
 */
url: string | null, 
/**
 * Timestamp when the snapshot was captured.
 */
captured_at: string | null, };
