// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type EnvironmentContextFullEvent = { 
/**
 * JSON serialization of the environment context snapshot.
 */
snapshot: JsonValue, 
/**
 * Sequence number associated with the snapshot emission.
 */
sequence: bigint | null, };
