// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type EnvironmentContextDeltaEvent = { 
/**
 * JSON serialization of the environment context delta.
 */
delta: JsonValue, 
/**
 * Sequence number associated with the delta emission.
 */
sequence: bigint | null, 
/**
 * Fingerprint of the baseline snapshot for this delta.
 */
base_fingerprint: string | null, };
