// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerFailure } from "./McpServerFailure";
import type { Tool } from "./Tool";

/**
 * Response payload for `Op::ListMcpTools`.
 */
export type McpListToolsResponseEvent = { 
/**
 * Fully qualified tool name -> tool definition.
 */
tools: { [key in string]?: Tool }, server_tools?: { [key in string]?: Array<string> } | null, server_failures?: { [key in string]?: McpServerFailure } | null, };
