// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Git/worktree context captured at review time.
 */
export type ReviewSnapshotInfo = { snapshot_commit?: string, branch?: string, worktree_path?: string, repo_root?: string, };
