// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewContextMetadata = { scope?: string, commit?: string, base_branch?: string, current_branch?: string, auto_review?: boolean, };
