// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewContextMetadata } from "./ReviewContextMetadata";

/**
 * Review request sent to the review session.
 */
export type ReviewRequest = { prompt: string, user_facing_hint: string, metadata?: ReviewContextMetadata, };
