// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from "./ConversationId";

export type SubAgentSource = "review" | "compact" | { "thread_spawn": { parent_thread_id: ConversationId, depth: number, } } | { "other": string };
