// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputMessageKind } from "./InputMessageKind";
import type { TextElement } from "./TextElement";

export type UserMessageEvent = { message: string, kind: InputMessageKind | null, images: Array<string> | null, 
/**
 * Local file paths sourced from `UserInput::LocalImage`.
 */
local_images: Array<string>, 
/**
 * UI-defined spans within `message` used to render or persist special elements.
 */
text_elements: Array<TextElement>, };
