#!/usr/bin/env bash
set -euo pipefail

APP_PATH="${APP_PATH:-/Applications/EveryCodeCompanion.app}"
BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"
INSTALL_CODE_SHIM=0
FORCE_OVERWRITE=0

usage() {
  cat <<'EOF'
Usage: scripts/install-ecc-shims.sh [options]

Install CLI wrapper shims that run the Every Code Companion bundled backend.

Options:
  --app PATH         App bundle path (default: /Applications/EveryCodeCompanion.app)
  --bin-dir PATH     Install directory for shims (default: ~/.local/bin)
  --install-code     Also install a `code` shim (default installs only `ecc`)
  --force            Overwrite an existing shim file
  -h, --help         Show this help text

Environment overrides:
  APP_PATH, BIN_DIR
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --app)
      APP_PATH="$2"
      shift 2
      ;;
    --bin-dir)
      BIN_DIR="$2"
      shift 2
      ;;
    --install-code)
      INSTALL_CODE_SHIM=1
      shift
      ;;
    --force)
      FORCE_OVERWRITE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

backend_dir="${APP_PATH}/Contents/Resources/backend"
bundled_code="${backend_dir}/code"
bundled_ecc="${backend_dir}/ecc"

if [[ ! -x "$bundled_code" ]]; then
  echo "Bundled backend not found: $bundled_code" >&2
  echo "Install or build EveryCodeCompanion so backend resources are present." >&2
  exit 1
fi

mkdir -p "$BIN_DIR"

install_wrapper() {
  local wrapper_name="$1"
  local target_binary="$2"
  local wrapper_path="${BIN_DIR}/${wrapper_name}"

  if [[ -e "$wrapper_path" && "$FORCE_OVERWRITE" -ne 1 ]]; then
    echo "Refusing to overwrite existing file: $wrapper_path" >&2
    echo "Re-run with --force to replace it." >&2
    exit 1
  fi

  cat > "$wrapper_path" <<EOF
#!/usr/bin/env bash
# generated by scripts/install-ecc-shims.sh
set -euo pipefail
exec "$target_binary" "\$@"
EOF
  chmod 755 "$wrapper_path"
}

if [[ -x "$bundled_ecc" ]]; then
  install_wrapper "ecc" "$bundled_ecc"
else
  install_wrapper "ecc" "$bundled_code"
fi

if [[ "$INSTALL_CODE_SHIM" -eq 1 ]]; then
  install_wrapper "code" "$bundled_code"
fi

echo "Installed shim(s) into: $BIN_DIR"
echo "  ecc -> ${bundled_ecc}"
if [[ "$INSTALL_CODE_SHIM" -eq 1 ]]; then
  echo "  code -> ${bundled_code}"
fi

case ":${PATH}:" in
  *":${BIN_DIR}:"*)
    ;;
  *)
    echo "Add to PATH to use shims in new shells:" >&2
    echo "  export PATH=\"${BIN_DIR}:\$PATH\"" >&2
    ;;
esac

